export const taskData = [
  {
    id: 1,
    date: "25 Aug",
    badge: { text: "4d", color: "bg-[#f42c2c1a] text-[#f42c2c]" },
    avatar: "DS",
    title: "Buyer's Initial Deposit",
    status: "Uploaded",
    statusColor: "text-[#2574eb]",
    hasSubtasks: true,
    subtasks: [
      {
        title: "Confirm deposit details",
        date: "25 Aug, 2025",
        badge: { text: "4d", color: "bg-[#f42c2c1a] text-[#f42c2c]" },
        background: "bg-[#2574eb14]",
      },
      {
        title: "Upload Receipt Document",
        date: "25 Aug, 2025",
        badge: { text: "4d", color: "bg-[#f42c2c1a] text-[#f42c2c]" },
        background: "bg-[#f4f4f573]",
      },
      {
        title: "Acknowledge Receipt",
        date: "25 Aug, 2025",
        badge: { text: "4d", color: "bg-[#f42c2c1a] text-[#f42c2c]" },
        background: "bg-[#f4f4f573]",
      },
    ],
  },
  {
    id: 2,
    date: "1 Sep",
    badge: { text: "11d", color: "bg-[#ffbc001a] text-[#ffbc00]" },
    avatar: "DS",
    title: "Condominium Document Rescission Expires",
    status: "Upload",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
  {
    id: 3,
    date: "1 Sep",
    badge: { text: "11d", color: "bg-[#ffbc001a] text-[#ffbc00]" },
    avatar: "DS",
    title: "Condo Fire Sprinkler Retrofit Review Contingency",
    status: "Upload",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
  {
    id: 4,
    date: "25 Aug",
    badge: { text: "4d", color: "bg-[#ffbc001a] text-[#ffbc00]" },
    avatar: "DS",
    title: "Homeowners' Association Disclosure Summary",
    status: "Upload",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
  {
    id: 5,
    date: "4 Sep",
    badge: { text: "14d", color: "bg-[#00d5311a] text-[#00d531]" },
    avatar: "DS",
    title: "Buyer's Additional Deposit",
    status: "Upload",
    statusColor: "text-zinc-900",
    hasSubtasks: true,
    subtasks: [
      {
        title: "Confirm deposit details",
        date: "4 Sep, 2025",
        badge: { text: "14d", color: "bg-[#00d5311a] text-[#00d531]" },
        background: "bg-[#f4f4f599]",
      },
      {
        title: "Upload Receipt Document",
        date: "4 Sep, 2025",
        badge: { text: "14d", color: "bg-[#00d5311a] text-[#00d531]" },
        background: "bg-[#f4f4f599]",
      },
      {
        title: "Acknowledge Receipt",
        date: "4 Sep, 2025",
        badge: { text: "14d", color: "bg-[#00d5311a] text-[#00d531]" },
        background: "bg-[#f4f4f599]",
      },
    ],
  },
  {
    id: 6,
    date: "30 Aug",
    badge: { text: "9d", color: "bg-[#ffbc001a] text-[#ffbc00]" },
    avatar: "DS",
    title: "Buyer's Loan Application",
    status: "Upload",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
  {
    id: 7,
    date: "9 Oct",
    badge: { text: "49d", color: "bg-[#00d5311a] text-[#00d531]" },
    avatar: "DS",
    title: "Buyer's Financing Contingency Deadline",
    status: "Use forms",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
    hasCheckbox: true,
  },
  {
    id: 8,
    date: "14 Sep",
    badge: { text: "24d", color: "bg-[#00d5311a] text-[#00d531]" },
    avatar: "DS",
    title: "Buyer Application for Association Approval",
    status: "Use forms",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
    hasCheckbox: true,
  },
  {
    id: 9,
    date: "9 Sep",
    badge: { text: "19d", color: "bg-[#ffbc001a] text-[#ffbc00]" },
    avatar: "DS",
    title: "Buyer's Inspection Period",
    status: "Use forms",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
    hasCheckbox: true,
  },
  {
    id: 10,
    date: "14 Sep",
    badge: { text: "24d", color: "bg-[#00d5311a] text-[#00d531]" },
    avatar: "DS",
    title: "Buyer's Election of Defective Inspection Items",
    status: "Use forms",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
  {
    id: 11,
    date: "19 Sep",
    badge: { text: "29d", color: "bg-[#00d5311a] text-[#00d531]" },
    avatar: "DS",
    title: "Buyer's Right to Terminate for Inspection Items",
    status: "Use forms",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
  {
    id: 12,
    date: "30 Nov",
    badge: { text: "101d", color: "bg-[#00d5311a] text-[#00d531]" },
    avatar: "DS",
    title: "Buyer's Survey Review & Objection Period",
    status: "Use forms",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
  {
    id: 13,
    date: "4 Dec",
    badge: { text: "105d", color: "bg-[#00d5311a] text-[#00d531]" },
    avatar: "DS",
    title: "Buyer's Walk-through Inspection",
    status: "Use forms",
    statusColor: "text-zinc-900",
    hasSubtasks: false,
  },
];

export const completedTasks = [
  {
    title: "Buyer's Initial Deposit",
    subtitle: "410 FLAGSHIP DR #501",
  },
];